bower.json
demo/index.html
demo/pro-grid-edit-column-demos.html
src/vaadin-pro-grid-edit-column.html
src/vaadin-pro-grid-inline-editing-mixin.html
test/edit-column.html

Fixes #14 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-pro/19)

feat(edit-column): add editModeRenderer support

---

demo/pro-grid-edit-column-demos.html
src/vaadin-pro-grid-edit-column-checkbox.html
src/vaadin-pro-grid-edit-column.html
test/edit-column.html
theme/lumo/vaadin-pro-grid-edit-column-checkbox.html
theme/lumo/vaadin-pro-grid-edit-column.html
theme/material/vaadin-pro-grid-edit-column-checkbox.html
theme/material/vaadin-pro-grid-edit-column.html

Fixes #15
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-pro/21)

Add boolean editor type support

---

.eslintrc.json
bower.json
demo/pro-grid-edit-column-demos.html
src/vaadin-pro-grid-edit-column-select.html
src/vaadin-pro-grid-edit-column-text-field.html
src/vaadin-pro-grid-edit-column.html
test/edit-column.html
theme/lumo/vaadin-pro-grid-edit-column-select.html
theme/lumo/vaadin-pro-grid-edit-column-text-field.html
theme/lumo/vaadin-pro-grid-edit-column.html
theme/material/vaadin-pro-grid-edit-column-select.html
theme/material/vaadin-pro-grid-edit-column-text-field.html
theme/material/vaadin-pro-grid-edit-column.html

Fixes #16
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-pro/23)

Add select editor type and editorOptions

---

demo/pro-grid-edit-column-demos.html
src/vaadin-pro-grid-edit-column.html
src/vaadin-pro-grid-inline-editing-mixin.html
test/edit-column.html

Fixes #11
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-pro/24)

Support edit on typing for text editor type

---

src/vaadin-grid-pro-edit-column.html
test/edit-column.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-pro/30)

fix(edit-column): ensure proper template and renderer observer calls

---

src/vaadin-grid-pro-inline-editing-mixin.html
test/edit-column.html

Fixes #28
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-pro/31)

fix(edit-column): cancel value change when exit edit mode on esc

---

demo/grid-pro-basic-demos.html
demo/grid-pro-common-modules-demos.html
demo/grid-pro-demo.js
demo/grid-pro-edit-column-demos.html

Fixes #20
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-pro/34)

Use separate items array for each grid demo [skip ci]

---

bower.json
src/vaadin-grid-pro.html

Fixes #32
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-pro/33)

chore(license): add vaadin-license-checker

---

theme/lumo/vaadin-grid-pro-edit-column-text-field.html

Fixes #36 
Regression introduced by vaadin/vaadin-text-field#299
Depends on vaadin/vaadin-text-field#300
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-pro/37)

Update text-field to latest alpha and fix flex regression

---

src/vaadin-grid-pro-edit-column.html
test/edit-column.html

Fixes #40
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-pro/54)

fix(edit-column): set focus-ring attribute on checkbox editor

---

src/vaadin-grid-pro-inline-editing-mixin.html
test/.eslintrc.json
test/basic.html
test/helpers.html

Fixes #47
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-pro/55)

fix: add missing imports check and warning

---

demo/grid-pro-edit-column-demos.html

Connected to vaadin/components-team-tasks#441

docs: move keep-editor-open demo [skip ci]

---

demo/grid-pro-edit-column-demos.html

Update demo to say that esc discards changes instead of saves changes.

Update demo to say that esc discards changes

---

src/vaadin-grid-pro-edit-select.html
src/vaadin-grid-pro-inline-editing-mixin.html
test/edit-column-type.html

fix(edit-column): restore cell focus on select editor confirm

---

src/vaadin-grid-pro-inline-editing-mixin.html
test/edit-column.html
theme/lumo/vaadin-grid-pro-styles.html
theme/material/vaadin-grid-pro-styles.html
theme/material/vaadin-grid-pro.html

fix(edit-column): show focus-ring on editable cell click

---

src/vaadin-grid-pro-edit-column.html
test/edit-column-type.html

Fix editorType resetting.

---

demo/grid-pro-edit-column-demos.html
src/vaadin-grid-pro-edit-select.html
test/edit-column.html

Fix tabbing through select column with keepEditorOpen

---

src/vaadin-grid-pro-inline-editing-mixin.html
test/edit-column.html

Connected to https://github.com/vaadin/vaadin-grid-pro-flow/issues/27

Stop click propagation on edit column, add tests

---

demo/grid-pro-edit-column-demos.html
src/vaadin-grid-pro-edit-column.html
test/edit-column.html

Add check for the path property

---

src/vaadin-grid-pro-edit-column.html

Remove unneeded check from default renderer

---

src/vaadin-grid-pro-inline-editing-mixin.html
test/.eslintrc.json
test/edit-column.html
test/helpers.html

fix: stop keydown event propagation on Enter

---

src/vaadin-grid-pro-inline-editing-mixin.html
test/edit-column.html

Fix GridPro setEnabled

---

.travis.yml
src/vaadin-grid-pro-inline-editing-mixin.html

Fixes https://github.com/vaadin/vaadin-grid-pro-flow/issues/85

fix: exit edit mode faster on focusout

---

src/vaadin-grid-pro-edit-column.html
test/.eslintrc.json
test/edit-column.html
test/helpers.html

feat: add editable-cell part attribute for theming

---

src/vaadin-grid-pro-inline-editing-mixin.html
test/edit-column.html

Fixes https://github.com/vaadin/vaadin-grid-pro/issues/117

fix: error thrown on details mousedown

---

src/vaadin-grid-pro-inline-editing-mixin.html
test/edit-column.html

fix: error thrown on details mousedown (#123)

---

src/vaadin-grid-pro-edit-column.html
src/vaadin-grid-pro-inline-editing-mixin.html

Connected to vaadin/vaadin-core#257

docs: add JSDoc for attributes [skip ci]

---

src/vaadin-grid-pro-inline-editing-mixin.html

fix: call blur from editor to trigger change event (#128)

---

.travis.yml
demo/grid-pro-edit-column-demos.html
src/vaadin-grid-pro-inline-editing-mixin.html
test/edit-column-renderer.html

Add ability to make cell edition to be performed on a single click
part of #73

feat: Edit on Click

---

src/vaadin-grid-pro-inline-editing-mixin.d.ts
src/vaadin-grid-pro-inline-editing-mixin.js

docs: add missing JSDoc annotation [skip ci]

---

src/vaadin-grid-pro-inline-editing-mixin.js
test/edit-column-overlay.test.js

fix: change timing for the stopEdit() call on focusOut cell editor

---

package.json
src/vaadin-grid-pro.html

cherry-pick of vaadin/web-components#3831 and vaadin/web-components#3832
related-to vaadin/web-components#3773

chore: Add cvdlName metadata

---

bower.json
package-lock-p3.json

Bump versions of the dependencies in Grid Pro.

chore: bump dependencies in bower.json

---

src/vaadin-grid-pro-edit-column.html
test/edit-column-template.html

Cherry pick of https://github.com/vaadin/vaadin-grid-pro/pull/199

fix: remove renderer before stamping template (CP: #199)
