- demo/pro-grid-edit-column-demos.html
- src/vaadin-pro-grid-edit-column.html
- src/vaadin-pro-grid-inline-editing-mixin.html
- test/edit-column.html
Needed for select type editor, to prevent exit edit mode when moving focus to `vaadin-select-overlay`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-pro/22)
> refactor(edit-column): use focusous instead of blur

- src/vaadin-grid-pro-edit-column.html
Same as #27. Turns out the Flow counterpart needs this workaround to make sure the web component default value is in sync and to prevent it from overriding the value set on the server side.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-pro/35)
> fix(edit-column): notify editor type change [skip ci]

- src/vaadin-grid-pro-inline-editing-mixin.html
- test/edit-column.html
Fixes #48 
Tested in Simulator. Have no idea how to test it better than dispatching 2 click events.
Also, disabled keyboard navigation tests for iOS as it does not make any sense there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-pro/56)
> fix: workaround dblclick entering edit mode iOS Safari

- demo/grid-pro-edit-column-demos.html
- src/vaadin-grid-pro-edit-select.html
- src/vaadin-grid-pro-inline-editing-mixin.html
- test/edit-column.html
These names have been found rather confusing and a bit too long. 
Suggested alternatives seem to be slightly more self-descriptive.
> Refactor: rename confusing preserveEditMode and allowEnterRowChange

- src/vaadin-grid-pro-edit-column.html
Required for the flow counterpart as it is always passing stringified value to the webcomponent.
> Check for string boolean value [skip ci]

- theme/lumo/vaadin-grid-pro-edit-select.html
- theme/lumo/vaadin-grid-pro-edit-text-field.html
Split lumo-grid-pro-edit-text-field style module to two parts and make it so that lumo-text-field styles are not automatically injected again to <vaadi-select-text-field> after the (semantically) more specific lumo-select-text-field styles.
This fixes an issue so that <vaadin-select> doesn't get a wrong cursor style when ever vaadin-grid-pro-edit-column.html or vaadin-grid-pro-edit-select.html is imported.
Fixes #75.
> Fix incorrect mouse cursor with Lumo theme

- demo/grid-pro-edit-column-demos.html
- src/vaadin-grid-pro-edit-column.html
- src/vaadin-grid-pro-inline-editing-mixin.html
- test/edit-column-renderer.html
Editor input is now selected from the light DOM with the query selector instead of taking the first child. Needed for the case when component is rendered with `flow-component-renderer`.
`cell-edit-started` event is now dispatched when the cell enters edit-mode. Mostly will be used internally with Flow, so no public API for it.
> Add edit event

- demo/grid-pro-edit-column-demos.html
- src/vaadin-grid-pro-edit-select.html
- src/vaadin-grid-pro-inline-editing-mixin.html
- test/edit-column-type.html
- test/edit-column.html
Connected to https://github.com/vaadin/vaadin-grid-pro-flow/issues/36
Switch from `keepEditorOpen` to `singleCellEdit`, update the tests and demos.
In most cases have replaced `select` to be at the end for easier usage apart from those with `zip-code` cause they should be logically in the end.
> Switch from keepEditorOpen to singleCellEdit

- src/vaadin-grid-pro-inline-editing-mixin.html
Fix #89. See the ticket for better description.
In this rare case, the first element in the click event's composed path
is tbody instead of the tr-element. For this reason, getEventContext()
can't find the targeted column. It's really unexpected that the composed
path doesn't start from the tr, even though the click clearly hits a
cell. Seems like a browser bug in this sense.
> Fix undefined column error when editor changes cell height

- src/vaadin-grid-pro-inline-editing-mixin.html
- test/.eslintrc.json
- test/edit-column-renderer.html
Fix #91
The problem was: When scrolling out of view, _updateItem is called,
which re-runs the renderer (in this case a custom edit mode renderer).
This would create a new renderer content without setting the model value
to it, right before the editor was closed, causing the empty value to be
saved to the model.
> fix: stop editing before re-running renderer

- bower.json
- src/vaadin-grid-pro-edit-column.html
- src/vaadin-grid-pro-edit-select.html
- src/vaadin-grid-pro-inline-editing-mixin.html
- test/edit-column-overlay.html
- test/edit-column-type.html
- test/edit-column.html
- test/test-suites.js
Fixes #94 
The PR includes the refactoring for `select` editor type which shouldn't break anything.
I came up with an idea how to get rid of the select wrapper, and it is needed for a more common workaround for `focusout` event (due to lack of `relatedTarget` on iOS 10).
> Fix focusout handling for editor components with overlay

- src/vaadin-grid-pro-edit-column.html
- src/vaadin-grid-pro-inline-editing-mixin.html
- test/edit-column-overlay.html
- test/edit-column.html
**Clarifications**:
1. `_editTemplateObserver` is now flushed in `ready` as `connectedCallback` is too early. One test is failing to prove that.
2. Listening to `internal-tabbing` in order to stop switching when working with `vaadin-custom-field`. Based on https://github.com/vaadin/vaadin-custom-field/pull/32
3. Also fixes #94
> Do not stop editing when interacting within the same cell.

- src/vaadin-grid-pro-inline-editing-mixin.html
- test/edit-column.html
Fixes #18 
It looks like Edge 18 has a bug with focus events not dispatched when focused node is removed from the DOM, at least I was able to reproduce that with `focusout`:
https://jsbin.com/socokoq/edit?html,js,console,output
Furthermore, we do not have all the focus events in place in the tests, so the issue is tricky to reproduce using mock events only.
The suggested fix is to add `keydown` listener in `vaadin-grid-pro` before it is added by `vaadin-grid`, to ensure that restoring cell focus by `vaadin-grid` happens **after** editor removal on <kbd>Esc</kbd>.
> fix: ensure cell is re-focused after exit edit mode

- src/vaadin-grid-pro.html
Connected to vaadin/components-team-tasks#492
This PR makes sure the license checker is only called when the component is created.
The static `_finalizeClass` method is needed to ensure we call it [once per class](https://github.com/Polymer/polymer/blob/f6ccc9d1bdc81e934e21bf27b3dba517b5840fd4/lib/mixins/properties-mixin.js#L138-L147).
> refactor: only run license checker when needed

- @types/interfaces.d.ts
- bower.json
- gen-tsd.json
- magi-p3-post.js
- package.json
- polymer.json
- src/vaadin-grid-pro-edit-column.html
- src/vaadin-grid-pro-inline-editing-mixin.html
Fixes #116 
Generated TS definitions look like this:
```ts
import {FlattenedNodesObserver} from '@polymer/polymer/lib/utils/flattened-nodes-observer.js';
import {get, set} from '@polymer/polymer/lib/utils/path.js';
import {GridColumnElement} from '@vaadin/vaadin-grid/src/vaadin-grid-column.js';
declare class GridProEditColumnElement extends GridColumnElement {
path: string|null|undefined;
editModeRenderer: GridBodyRenderer|undefined;
editorOptions: string[];
editorType: GridProEditorType;
editorValuePath: string;
ready(): void;
_prepareBodyTemplate(): HTMLTemplateElement|null;
_selectFirstTemplate(header?: boolean, footer?: boolean, editor?: boolean): HTMLTemplateElement|null;
_findTemplate(header: boolean, footer: boolean, editor?: boolean): HTMLTemplateElement|null; …
```
> feat: prepare for TS defs generation [skip ci]

- src/vaadin-grid-pro-inline-editing-mixin.html
- test/edit-column.html
Part of https://github.com/vaadin/vaadin-grid-pro-flow/issues/94.
`vaadin-grid-pro-flow` relies on getting the custom editor value from the server side and most of Vaadin components (if not all), by default, updates its value from a change event on the client side. The way the editor is removed on pressing `Tab`/`Enter`, browsers such Firefox and Safari won't trigger a `change` event when the DOM element is removed. Forcing a call to `editor.blur()` before the element is removed could solve this issue.
> fix: call blur from editor to trigger change event

- src/vaadin-grid-pro-inline-editing-mixin.js
Added JSDoc annotation for the `cell-edit-started` event which was missing from the [API docs](https://cdn.vaadin.com/vaadin-grid/6.0.0-alpha1/#/elements/vaadin-grid#events).
> chore: align events JSDoc annotations [skip ci]

- test/edit-column-renderer.test.js
Fixes #161 
The test seems to create some kind of an edge case that makes the grid generate more physical rows than usually. This has something to do with reassigning the `items` in the test right after it's been assigned in the beforeEach block (with a smaller array). This is still a regression from https://github.com/vaadin/vaadin-grid/commit/38a01c5ab889cf088e76a3e675ee94fe60a273b8 and has a [separate issue](https://github.com/vaadin/vaadin-grid/issues/2134) report in `vaadin-grid`
Fix for the test; set items `null` before reassigning it to workaround the issue.
> test: workaround a grid regression

- src/vaadin-grid-pro-inline-editing-mixin.html
- test/edit-column-overlay.html
- test/edit-column-renderer.html
- test/index.html
* fix: clear items list before calling `Array.apply()` and flush grid
>  fix: change timing for the stopEdit() call on focusOut cell editor (CP:  #165)

- src/vaadin-grid-pro-edit-column.html
- test/edit-column-template.html
Fixes https://github.com/vaadin/flow-components/issues/4907
Note: bug is reproducible only in v14
It is possible from time to time reproduce the issue with the provided reproducible example application (network throttling should be enabled).
Following the best guess on what is causing that the simplified version of the example is created (forked from the provided repo):
- https://github.com/yuriy-fix/grid-pro-issue/blob/main/src/main/java/org/vaadin/example/MainView.java
- https://github.com/yuriy-fix/grid-pro-issue/blob/main/src/test/java/org/vaadin/example/MainViewIT.java (test to constantly reproduce the issue)
Selecting an item when editor is opened will lead to an item update with editor renderer (within `_updateItem`) via model assignment. Need to make sure that editor renderer is …
> fix: remove renderer before stamping template
